#### Name: 吳宜庭
#### Class: 資管系三年級
#### SID: s05490055
#### Program Name: hw1_ s05490055.ipynb
#### Function: 本次作業包含三個大題，有關陣列使用、亂數與一些統計公式
#### Homework: No.1
#### Limitations: (1). 限用 NumPy 指令語法
#### Date: 2019/04/18

### P1-1 以 NumPy 內建工具來產生 60 個介於 -50 到 +99 之間的亂數整數，每一個整數大小為 64 位元。將這 60 個整數任意放入一個 6X10 的陣列中，以每一列(row)為單位，”分別”計算並輸出以下需求(數值需四捨五入制小數點後兩位數)：

In [1]:
import numpy as np
randarr = np.random.randint(-50,100,[6,10],dtype='i8')
#print(randarr)

#### a、 資料集的型態

In [2]:
print("a、資料集的型態 =", randarr.dtype, "\n")

a、資料集的型態 = int64 



#### b、 平均數

In [3]:
#np.around(decimal=2)將元素取至小數點第二位四捨五入、axis=0以列為單位計算
rmean = np.around(np.mean(randarr, axis=0), decimals=2)
print("b、平均數 =", rmean, "\n")

b、平均數 = [ 9.   22.67 29.17 37.5  49.5  18.    2.33 23.   35.5  23.  ] 



#### c、 中位數

In [4]:
rmedian = np.around(np.median(randarr, axis=0), decimals=2)
print("c、中位數 =", rmedian, "\n")

c、中位數 = [ 2.5 31.  25.5 47.  62.   7.5 -1.5 29.  47.5 22. ] 



#### d、 標準差

In [5]:
rstd = np.around(np.std(randarr, axis=0), decimals=2)
print("d、標準差 =", rstd, "\n")

d、標準差 = [45.52 24.37 51.84 51.21 36.45 20.48 35.3  40.9  39.54 51.89] 



#### e、變異數

In [6]:
rvar = np.around(np.var(randarr, axis=0), decimals=2)
print("e、變異數 =", rvar, "\n")

e、變異數 = [2072.33  593.89 2687.14 2622.58 1328.58  419.33 1246.22 1673.   1563.58
 2693.  ] 



#### f、 集差值 ( 請參考如何使用 numpy.ptp())，本題要的是特定一列極差值。 

In [7]:
#取出每一列的集差值後再取某特定列
rptp = np.around(np.ptp(randarr, axis=0), decimals=2)
#print("f、集差值 =", rptp)
print("f、特定列集差值 =", rptp[1], "\n") #取第二列極差值

f、特定列集差值 = 72 



### P1-2 以 NumPy 內建工具來產生一個 3X4 的陣列 A，以及一個 4X5 的陣列 B，每一個陣列的元素為介於 1 到 50 之間的亂數整數，每一個整數大小為 32 位元。請完成以下的需求：

#### a、 顯示陣列 A和陣列 B

In [8]:
print("a、顯示陣列 A和陣列 B")
A3x4 = np.random.randint(1,51,[3,4], dtype = 'i4')
print("A =>\n",A3x4, "\n")
B4x5 = np.random.randint(1,51,[4,5], dtype = 'i4')
print("B =>\n",B4x5, "\n")

a、顯示陣列 A和陣列 B
A =>
 [[39 28 37 14]
 [30 10 41 22]
 [10 20  5 28]] 

B =>
 [[42 31 44 36 22]
 [18  1  5  3 11]
 [ 2 23 34  1 42]
 [38 49 16 32 46]] 



#### b、 找出陣列 A中每一列 的最大值。

In [9]:
Amax = np.around(np.max(A3x4,axis=0))
print("b、陣列 A 中每一列最大值 =",Amax, "\n")

b、陣列 A 中每一列最大值 = [39 28 41 28] 



#### c、 找出陣列 A第二列 中所有小於 30 的數值 。

In [10]:
#先找出第二列中所以小於30的數值的索引值放入arrA，再利用for迴圈方式去將值append進ARR裡
arrA = np.where(A3x4[1]<30)
ARR=[]
for ele in arrA[0]:
    ARR.append(A3x4[1][ele])
print("c、陣列 A 第二列中所有小於 30 =",ARR, "\n")

c、陣列 A 第二列中所有小於 30 = [10, 22] 



#### d、 找出陣列 B中每一行 或欄 的最大值。

In [11]:
Bcolumnmax = np.around(np.max(B4x5,axis=1))
print("d、陣列 B 中每一行或欄最大值 =",Bcolumnmax, "\n")

d、陣列 B 中每一行或欄最大值 = [44 18 42 49] 



#### e、 找出陣列 B第二行 中所有小於 30 的數值。

In [12]:
arrB = np.where(B4x5[:][1]<30)
BRR=[]
for ele in arrB[0]:
    BRR.append(B4x5[1][ele])
print("e、陣列 B 第二行中所有小於 30 =",BRR, "\n")

e、陣列 B 第二行中所有小於 30 = [18, 1, 5, 3, 11] 



#### f、 顯示陣列 A中第一列 和陣列 B中第一列 的聯集結果。

In [13]:
print("f、陣列 A 第一列與陣列 B 第一列 聯集結果 =",np.union1d(A3x4[0],B4x5[0]), "\n")

f、陣列 A 第一列與陣列 B 第一列 聯集結果 = [14 22 28 31 36 37 39 42 44] 



#### g、 計算與輸出陣列 A 與陣列 B 相乘的結果。

In [14]:
print("g、陣列 A與陣列 B 相乘 =>\n",np.dot(A3x4,B4x5), "\n")

g、陣列 A與陣列 B 相乘 =>
 [[2748 2774 3338 1973 3364]
 [2358 2961 3116 1855 3504]
 [1854 1817 1158 1321 1938]] 



#### h、 將兩個陣列扁平化後，輸出陣列 A 交集 陣列 B 的集合運算結果。

In [15]:
print("h、陣列 A 交集 陣列 B =",np.intersect1d(A3x4.flatten(),B4x5.flatten()), "\n")

h、陣列 A 交集 陣列 B = [ 5 22] 



#### i、 同上一題，輸出陣列 A 差集 陣列 B 的集合運算結果。

In [16]:
print("i、陣列 A 差集 陣列 B =",np.setdiff1d(A3x4.flatten(),B4x5.flatten()), "\n")

i、陣列 A 差集 陣列 B = [10 14 20 28 30 37 39 41] 



### P1-3 以 NumPy 內建工具來產生一個 5X5 的陣列 A，以及一個 5X5 的陣列 B，其中陣列 A 的元素為介於 1 到 50 之間由小到大的奇數，而陣列 B 的元素為介於 1 到 50 之間由小到大的偶數，每一個整數元素的大小為 32 位元。請完成以下的需求：

#### a、 顯示陣列 A 和陣列 B

In [17]:
print("a、 顯示陣列 A 和陣列 B")
#先各做一個全是偶數與全是奇數的陣列，在轉換成5x5的矩陣
even_A  = np.reshape(np.arange(2, 51, 2, dtype = 'i4'),(5,5))
odd_B = np.reshape(np.arange(1, 51, 2, dtype = 'i4'),(5,5))
A = np.copy(even_A)
B = np.copy(odd_B)
print("A =>\n",even_A, "\n")
print("B =>\n",odd_B, "\n")

a、 顯示陣列 A 和陣列 B
A =>
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]] 

B =>
 [[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]] 



#### b、 將陣列 A 與陣列 B 作垂直堆疊並顯示結果。

In [18]:
print("b、陣列 A 與陣列 B 垂直堆疊 =\n",np.vstack([A,B]), "\n")

b、陣列 A 與陣列 B 垂直堆疊 =
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]] 



#### c、 將陣列 A 與陣列 B 作水平堆疊並顯示結果。

In [19]:
print("c、將陣列 A 與陣列 B 水平堆疊 =\n",np.hstack([A,B]), "\n")

c、將陣列 A 與陣列 B 水平堆疊 =
 [[ 2  4  6  8 10  1  3  5  7  9]
 [12 14 16 18 20 11 13 15 17 19]
 [22 24 26 28 30 21 23 25 27 29]
 [32 34 36 38 40 31 33 35 37 39]
 [42 44 46 48 50 41 43 45 47 49]] 



#### d、 陣列 A 和陣列 B 中的奇數列進行交換，並顯示交換後兩個陣列的內容。

In [20]:
A[:, ::2] = odd_B[:, ::2]
B[:,::2] = even_A[:,::2]
print("d、陣列A與陣列B 中的奇數列交換後")
print("A =>\n",A, "\n")
print("B =>\n",B)

d、陣列A與陣列B 中的奇數列交換後
A =>
 [[ 1  4  5  8  9]
 [11 14 15 18 19]
 [21 24 25 28 29]
 [31 34 35 38 39]
 [41 44 45 48 49]] 

B =>
 [[ 2  3  6  7 10]
 [12 13 16 17 20]
 [22 23 26 27 30]
 [32 33 36 37 40]
 [42 43 46 47 50]]
